# Generated by Django 3.2.9 on 2021-12-25 19:52

import cga_booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multi_relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('taggeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_relation.taggeditem')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=('multi_relation.taggeditem',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('address', models.CharField(max_length=255, unique=True)),
                ('coordinate', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('external_appearance', models.ImageField(blank=True, null=True, upload_to=cga_booking.models.hotel_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='InternalPhoto',
            fields=[
                ('textitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_relation.textitem')),
                ('path', models.ImageField(blank=True, null=True, upload_to=cga_booking.models.room_upload_path)),
            ],
            bases=('multi_relation.textitem',),
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('textitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_relation.textitem')),
                ('content_flag', models.PositiveSmallIntegerField(choices=[(1, 'Overview'), (2, 'Title'), (3, 'Content'), (4, 'Cautions'), (5, 'Other')], default=3)),
                ('sequence', models.PositiveIntegerField(default=1)),
            ],
            bases=('multi_relation.textitem',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
