# Generated by Django 3.2.9 on 2021-12-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cga_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='belongs2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cga_booking.hotel'),
        ),
    ]
