# Generated by Django 3.2.9 on 2021-12-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cga_booking', '0002_room_belongs2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='double_bed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='single_bed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
