# Generated by Django 3.2.9 on 2021-12-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cga_booking', '0003_auto_20211226_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
