# Generated by Django 3.2.9 on 2021-12-31 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi_relation', '0002_reservation'),
        ('cga_booking', '0004_alter_hotel_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_relation.reservation')),
                ('usage', models.PositiveSmallIntegerField(choices=[(1, 'Official Business'), (2, 'Guidance'), (3, 'Family Visit'), (4, 'Other')], default=4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('multi_relation.reservation',),
        ),
    ]
