# Generated by Django 3.2.9 on 2021-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_relation', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='serial_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
