# Generated by Django 3.2.9 on 2022-01-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_relation', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Unsend')], default=1),
        ),
    ]
