# Generated by Django 3.2.9 on 2022-01-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_relation', '0006_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_time']},
        ),
    ]
