# Generated by Django 3.2.9 on 2021-11-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='contact',
            new_name='contact_phone',
        ),
    ]
