# Generated by Django 3.2.9 on 2021-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0002_rename_contact_station_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.PositiveIntegerField(choices=[(0, 'Chose the region'), (1, 'Northern'), (2, 'Central'), (3, 'Southern'), (4, 'Eastern')], default=0),
        ),
    ]
