# Generated by Django 3.2.9 on 2021-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0003_alter_station_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Overview'), (2, 'Title'), (3, 'Subtitle'), (4, 'Content'), (5, 'Explanation'), (6, 'Traffic Information'), (7, 'Cautions')], default=4),
        ),
    ]
