# Generated by Django 3.2.9 on 2021-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0005_auto_20211127_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Display')], default=2),
        ),
    ]
