# Generated by Django 3.2.9 on 2022-01-22 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0007_auto_20211226_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='introductions',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
