# Generated by Django 3.2.9 on 2022-01-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgaforum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
