# Generated by Django 3.2.9 on 2021-11-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID_Number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
