# Generated by Django 3.2.9 on 2021-11-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID_Number_is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
