# Generated by Django 3.2.9 on 2022-01-18 02:23

import cga_case.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True)),
                ('source_url', models.URLField(unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('handling_point', models.TextField(null=True)),
                ('cautions', models.TextField(null=True)),
                ('flow_chart', models.ImageField(blank=True, null=True, upload_to=cga_case.models.case_flow_chart_upload_path)),
                ('is_one_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cga_case.casecategory')),
                ('legal_resources', models.ManyToManyField(null=True, to='cga_case.LR')),
            ],
        ),
    ]
