# Generated by Django 3.2.9 on 2022-01-22 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cga_case', '0004_alter_lr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cautions',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='handling_point',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
