# Generated by Django 3.2.9 on 2022-01-22 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cga_case', '0005_auto_20220122_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lr',
            name='content',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
