# Generated by Django 3.2.9 on 2022-01-23 23:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cga_case', '0007_auto_20220122_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cautions',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='handling_point',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='legal_resources',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
    ]
